# FROM node:14-alpine as build

# WORKDIR /usr/src/app

# COPY package*.json ./

# RUN npm install

# COPY . .

FROM node:14-alpine
RUN mkdir -p /svr/app
WORKDIR /svr/app
RUN npm i -g @nestjs/cli --silent
COPY package.json .
RUN npm install --silent
COPY . .
# Value set in .env file.
EXPOSE $BACKEND_PORT
# EXPOSE 3004
# CMD ["npm", "run", "start:debug"]
CMD ["npm", "run", "dev"]